name: Daily Cleanup

on:
  workflow_dispatch:
    # No inputs
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  run-cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "^1.20"

      - name: Create config.json
        run: |
          echo "{\"baseURL\": \"$BSKY_BASE_URL\", \"handle\": \"$BSKY_HANDLE\", \"password\": \"$BSKY_PASSWORD\", \"dayCount\": $BSKY_DAY_COUNT}" > config.json
        env:
          BSKY_BASE_URL: ${{ secrets.BSKY_BASE_URL }}
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          BSKY_DAY_COUNT: ${{ secrets.BSKY_DAY_COUNT }}

      - name: Run cleanup script
        run: |
          go run bskycleanup.go ${BSKY_FLAGS:-}
        env:
          BSKY_FLAGS: ${{ secrets.BSKY_FLAGS }}